#!/bin/bash
#
# System Report Script
# Author: Jimin Yang
# Student ID: 200637958
# Description: Generates a detailed system information report for any Linux system.

# -------------------- GATHER DATA --------------------
# Basic system info
HOSTNAME=$(hostname)
USERNAME=$(whoami)
DATE=$(date)

# OS Information
source /etc/os-release
OS="$NAME $VERSION"

# Uptime
UPTIME=$(uptime -p)

# CPU Info
CPU=$(lshw -class processor 2>/dev/null | grep -m1 'product:' | sed 's/.*product: //')

# RAM Info
RAM=$(free -h | awk '/^Mem:/ {print $2}')

# Disk Info
DISKS=$(lshw -class disk 2>/dev/null | awk -F: '/product|size/ {gsub(/^[ \t]+/, "", $2); printf "%s ", $2; if ($1 ~ /size/) print "";}' | paste -sd "," -)

# Video Card
VIDEO=$(lshw -class display 2>/dev/null | grep 'product:' | sed 's/.*product: //')

# Host IP Address (connected to default gateway)
DEFAULT_IFACE=$(ip route | awk '/default/ {print $5}' | head -n1)
HOST_IP=$(ip -4 addr show "$DEFAULT_IFACE" | awk '/inet / {print $2}' | cut -d/ -f1)

# Default Gateway
GATEWAY=$(ip route | awk '/default/ {print $3}' | head -n1)

# DNS Server
DNS=$(grep "nameserver" /etc/resolv.conf | awk '{print $2}' | paste -sd "," -)

# -------------------- SYSTEM STATUS --------------------
# Logged In Users
USERS=$(who | awk '{print $1}' | sort | uniq | paste -sd "," -)

# Disk Space
DISK_SPACE=$(df -h --local | awk 'NR>1 {print $6 " " $4}' | paste -sd "," -)

# Process Count
PROCESS_COUNT=$(ps -e --no-headers | wc -l)

# Load Averages
LOAD_AVG=$(uptime | awk -F'load average:' '{print $2}' | sed 's/ //g')

# Listening Ports
LISTEN_PORTS=$(ss -tuln | awk 'NR>1 {print $5}' | awk -F: '{print $NF}' | sort -n | uniq | paste -sd "," -)

# UFW Status
UFW_STATUS=$(sudo ufw status | head -n1 2>/dev/null)

# -------------------- OUTPUT REPORT --------------------
cat <<EOF

System Report for $HOSTNAME generated by $USERNAME, on $DATE

System Information
------------------
OS: $OS
Uptime: $UPTIME
CPU: $CPU
RAM: $RAM
Disk(s): $DISKS
Video: $VIDEO
Host Address: $HOST_IP
Gateway IP: $GATEWAY
DNS Server: $DNS

System Status
-------------
Users Logged In: $USERS
Disk Space: $DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVG
Listening Network Ports: $LISTEN_PORTS
UFW Status: $UFW_STATUS

EOF
